print("Please input the following information:")
print()

First_name = input("First name: ")
Last_name = input("Last name: ")
email_address = input("Email address: ")
phone_number = input("Phone number: ")
Job_title = input("Job title: ")
ID_number = input("ID number: ")
print()

print("The ID card is:")
print("--------------------------------------------------------------")
print(f"{Last_name.upper()}, {First_name.capitalize()}")
print(Job_title.title())
print(ID_number)
print()
print(email_address.lower())
print(phone_number)
print("--------------------------------------------------------------")
